### ISSUE TITLE
Should Oculus Touch report the thumbrest button

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr-input-profiles#100]
@Artyom17 What does Oculus prefer?  Currently the Oculus Touch registry profile includes the thumbrest, but I seem to recall hearing that wasn't actually the desired behavior?

**Comment by Artyom17** [comment]
I am not sure why wouldn't we want to expose the thumbrest as a capacitive button. It is exposed in our PC SDK. The only thing - the thumbrest is not present for the second edition of the Oculus Touch (Rift S and Quest). If we have different profiles for Rift's Oculus Touch and for Rift S/Quest's ones then we can expose thumbrest for the former and do not expose it for the latter (or expose as a dummy button with unchanging state; in fact, this is what we do in Oculus Browser when exposing Quest's Oculus Touch via Gamepad API. The layout of the buttons is as follows:
------
0 - thumbstick
1 - trigger
2 - grip
3 - X / A
4 - Y / B
5 - dummy thumbrest
------
This layout is compatible with what Chrome and Mozilla has for Rift)

**Comment by NellWaliczek** [comment]
(Just to double check... this index ordering is for WebVR not WebXR correct?)

Ok, so if that's the case, (the Quest will have no thumbrest reported, but the Touch will) we either need to say that the Quest cannot fall back to the Touch OR we need to resolve #79 asap.

**Comment by Artyom17** [comment]
Yes, WebVR. And WebXR, if gamepads are enabled for WebXR (which is currently the case for Oculus Browser, till we ship this module).

**Comment by NellWaliczek** [comment]
Looks like this was resolved by https://github.com/immersive-web/webxr-input-profiles/commit/5974b67ff095d7e7f453522a7f100465b2af89fd
