### ISSUE TITLE
Empty "visualResponses" - allowed or not?

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/webxr-input-profiles#115]
According to the README.md the empty array for visualResponses is possible, but in fact the checker fails:
[16:03:56] Error: undefined Failed to validate schema with errors: [
  {
    "keyword": "minItems",
    "dataPath": ".layouts.left.components['thumbrest'].visualResponses",
    "schemaPath": "visualResponses.schema.json/minItems",
    "params": {
      "limit": 1
    },
    "message": "should NOT have fewer than 1 items"
  }
]

I need to create an "dummy thumbrest" for oculus-touch-v2 (https://github.com/immersive-web/webxr-input-profiles/pull/113), how do I do it, if empty visualResponses is not allowed?
And anyway, either the validator or README.md should be fixed.

**Comment by NellWaliczek** [comment]
Ah, that sounds like a schema bug.  Feel free to remove the minItems property as part of your PR.

**Comment by NellWaliczek** [comment]
Thanks for fixing this!
