### ISSUE TITLE
Support "windows-mixed-reality" as a fallback name?

### ISSUE THREAD

**Issue by klausw** [immersive-web/webxr-input-profiles#116]
**Profile ID**
microsoft-mixed-reality

**Expected behavior**
Unfortunately, Chrome v79 has shipped with the fallback profile name `windows-mixed-reality` instead of `microsoft-mixed-reality` as used in the registry. See Chromium issue https://crbug.com/1033075 and [code search results](https://cs.chromium.org/search/?q=windows-mixed-reality&sq=package:chromium).

The "windows-mixed-reality" name seems to have been independently picked for the currently-enabled-by-default _windows_mixed_reality/_ driver and Microsoft's contributed _openxr/_ driver.

The polyfill was also using "windows-mixed-reality" until recently. @toji updated the name [a month ago](https://github.com/immersive-web/webxr-polyfill/commit/45cc9b01e9257dc8861aa7c0a0fc3fdb08884bb6#diff-17ea53cf6f8464bfcfad7c0aa3480ef6), but it seems that people didn't notice the mismatch with the native implementations at the time.

It's too late to change this for Chrome 79, and while this can be changed for the next Chrome version, I'm wondering if it would be feasible to introduce the "windows-mixed-reality" name as an alias, or renaming the fallback profile to that, to fit with the principle of least surprise, and to avoid compatibility issues during the transition? @dmarcos had reported this while working on A-Frame, and dealing with the inconsistency may require workarounds.

@Manishearth said that Servo doesn't currently have profiles implemented. @kearwood, do you have information about current support?

(Apologies for getting the name wrong in the Chrome implementation, but I suspect this may be an issue of people not having noticed that their assumed name doesn't actually match the registry name - it took me a minute to figure out what was wrong when looking at the bug report.)

**Comment by Manishearth** [comment]
Note that the only device backend Servo supports is Hololens, and we're still figuring out what input profile strings for hands are supposed to look like.

We have a couple other backends, but they're mostly for testing. We also have an Android backend implemented but not yet hooked up.
