### ISSUE TITLE
Consider to remove thumbrest from Oculus Touch 2 profile

### ISSUE THREAD

**Issue by daoshengmu** [immersive-web/webxr-input-profiles#168]
**Profile ID**
The ID of the profile 
oculus-touch-v2

**Expected behavior**
Based on my testing with Oculus mobile SDK, I never got the thumbrest event successfully from Oculus Quest controller. I know this event exists in Oculus Touch v1 controller of Oculus Rift.  Therefore, I wonder if we still need to keep it in the `oculus-touch-v2` profile, perhaps removing it would be a good idea.

@rcabanier  I know Oculus browser might have defined it your codebase, but as a developer of Firefox Reality, I feel that if this button is not working. we probably should remove it. How do you feel about it?

**Comment by Manishearth** [comment]
cc @Artyom17 @cabanier

**Comment by Artyom17** [comment]
This was discussed multiple times (#79, #100, #109). The decision was to leave the thumbrest for Oculus Touch v2, since it inherits from Oculus Touch v1.
