### ISSUE TITLE
Privacy issue with using CDN and workarounding it  via mirroring? 

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/webxr-input-profiles#179]
This issue was recently raised by our team, while we were deciding how to render controllers in our WebXR experience. The issue is that potentially the CDN can see and collect the origin of such requests, analyze the traffic and so on.
As a potential workaround there is an idea to mirror the CDN using our company's infra.
Thus, the questions are:
* Are the privacy concerns legit?
* What do you think of using mirrored CDN? Does anyone else do this?

**Comment by o0-dh-0o** [comment]
Another way to frame this — assuming we’re not the only consumer of this API that would want to host controller content on our own CDN but still would like to use the controller-selection functionality, would it be possible to modify the API to let a user plug in their own content path?

**Comment by davehill00** [comment]
Another way to frame this — assuming we’re not the only consumer of this API that would want to host controller content on our own CDN but still would like to use the controller-selection functionality, would it be possible to modify the API to let a user plug in their own content path?

**Comment by Artyom17** [comment]
@davehill00 
The CDN's url is not a part of API, it is specified in your experience, you can easily change it to something more private. Once you make full mirror of CDN you can use the controller-selection functionality. But you'll need to manually sync the CDNs periodically.

**Comment by toji** [comment]
Artem is correct. The library has no default API, but some popular libraries (like Three.js) will have a default CDN they point to. Even in that case, though, it can be overridden.

Anyone is free to either choose a different CDN or clone this repo and serve the assets from their own host.
