### ISSUE TITLE
Viewer is currently broken and does not display any 3D content or profile information.

### ISSUE THREAD

**Issue by msub2** [immersive-web/webxr-input-profiles#218]
**Describe the bug**
The viewer is failing to load any of its 3D page content or profile information.

**To Reproduce**
1. Go to https://immersive-web.github.io/webxr-input-profiles/packages/viewer/dist/index.html
2. Observe that the page is not currently functional.

**Expected behavior**
Page should be displaying the viewer and loading profiles.

**Screenshots**
![](https://cdn.discordapp.com/attachments/805647111625375764/951271244093849690/unknown.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 98/Firefox 98

**Additional Context**
I pulled the repo, built, and tested locally and the page loaded just fine, so I'm not sure what's going wrong here. There was a dependabot update that updated three.js from r113 to r137, but that may or may not have affected it.

**Comment by msub2** [comment]
I've figured out the issue, the three.js update did in fact break things since they switched to using bare imports for three in the example files. Adding an importmap in the index.html seems to fix this, but there's now other issues since we're jumping 20+ versions. I'll try and iron this out and PR.

**Comment by cabanier** [comment]
@toji Maybe we can downgrade three.js to 127?
I verified that it fixes the problem

**Comment by toji** [comment]
Reverting to 127 sounds good to me.

**Comment by toji** [comment]
Pushed https://github.com/immersive-web/webxr-input-profiles/commit/614bf32b8e8ba7a81c05b21f8e47a860ea34a94c. Works locally, I'll keep an eye on it to see if it deploys properly.

**Comment by msub2** [comment]
Deployment looks good! I'll send in a PR later to address a couple API changes in three.js.
