### ISSUE TITLE
Latest version of hands doesn't have skinning anymore

### ISSUE THREAD

**Issue by hybridherbst** [immersive-web/webxr-input-profiles#233]
**Profile id**
generic-hand

**Describe the bug**
Looks like while in https://cdn.jsdelivr.net/npm/@webxr-input-profiles/assets@1.0/dist/profiles/generic-hand/, `left.glb` and `right.glb` both are ~90kB and contain skinning information, in the latest version in this repo they don't have that anymore (and are ~60kB).
I also ran `npm run build` but I think that just copies them over and does not modify them (size stays ~60kB and they don't have skinning info).

**To Reproduce**
1. Go to https://cdn.jsdelivr.net/npm/@webxr-input-profiles/assets@1.0/dist/profiles/generic-hand/ (the one referenced by three.js when fetching hand models)
2. download left.glb
3. Check with any glTF viewer for the existance of skinning information
4. Note that it has skinning information
5. Check with latest left.glb and right.glb
6. They have a rotation change (https://github.com/immersive-web/webxr-input-profiles/pull/226) but also don't have skinning information anymore.

**Expected behavior**
Skinning :)

**Screenshots**
**1.0.12 (with skinning):**
![image](https://user-images.githubusercontent.com/2693840/197523124-e011ae06-9839-4477-98c3-41f3017d97c6.png)

**Now (no skinning):**
![image](https://user-images.githubusercontent.com/2693840/197523166-554bc149-6417-4b35-b742-988f557ba48d.png)

**Comment by intrepidOlivia** [comment]
Looks like this information was stripped out during an optimization step. Want to look at my pull request and see if it has the information you expect? https://github.com/immersive-web/webxr-input-profiles/pull/235

**Comment by cabanier** [comment]
@hybridherbst  can you verify that this is working for you now?

**Comment by hybridherbst** [comment]
Skinning data is there, but bones are now all rotated @cabanier 

![com oculus shellenv-20221031-210525](https://user-images.githubusercontent.com/2693840/199101391-e95be1b9-9192-4361-97ea-f8e3deaafbc2.jpg)

I believe you ran into the same Blender trap as I did a while ago for the "Monster Hands": 
https://twitter.com/hybridherbst/status/1584524129054904321

**Comment by hybridherbst** [comment]
If you want, you can quickly test by
- going to https://glitch.com/edit/#!/three-xr?path=index.html%3A220%3A100
- remixing it
- dropping your left.glb and right.glb into "assets"
- copying the path into index.html:220
(that's how I just tested your new models)

**Comment by toji** [comment]
> Is there a good place to add this kind of info right in this repository? E.g. https://github.com/immersive-web/webxr-input-profiles/blob/main/packages/assets/tutorial/README.md?

I'm not sure how frequently that tutorial is referenced, but this kind of exporting tip definitely fits well with the rest of the content in that document. Feel free to put up a pull request to add it, because I feel that's a valuable bit of info!

**Comment by intrepidOlivia** [comment]
Sorry for the delay on this, I've updated pull request https://github.com/immersive-web/webxr-input-profiles/pull/235 to include skinning while maintaining proper rotation and bone placement.

**Comment by cabanier** [comment]
> Sorry for the delay on this, I've updated pull request #235 to include skinning while maintaining proper rotation and bone placement.

Have you verified that the hand still work in xr?

**Comment by intrepidOlivia** [comment]
> Have you verified that the hand still work in xr?

I personally did, a second source of verification would be welcome.

**Comment by cabanier** [comment]
> > Have you verified that the hand still work in xr?
> 
> I personally did, a second source of verification would be welcome.

@hybridherbst can you try? You found the original problem

**Comment by hybridherbst** [comment]
Can confirm it works as hands again! 
But I'm not sure about the orientation when using it as default controller now (which I think was the original intent behind changing them in the first place)

**Comment by cabanier** [comment]
> Can confirm it works as hands again! But I'm not sure about the orientation when using it as default controller now (which I think was the original intent behind changing them in the first place)

Are they oriented the wrong way again?

**Comment by sylwesterdigital** [comment]
It has been some time since @hybridherbst identified an issue with the mesh. I can verify that these GLB files function correctly. However, when attempting to create custom hand designs by importing these models into Blender, I encounter a challenge. While I can modify the material without issues, upon re-exporting them as GLB, there seems to be a misalignment in their orientation. Could anyone provide guidance on how to import/export from Blender, please?
<img width="797" alt="before" src="https://github.com/immersive-web/webxr-input-profiles/assets/27820237/f3c5be9f-9986-46c0-9f4a-7fe002775291">
<img width="770" alt="after" src="https://github.com/immersive-web/webxr-input-profiles/assets/27820237/0a40d6bb-bd00-45e5-9938-259117802a9d">
https://youtube.com/shorts/uKJGmGdi7mk?si=2BxVdYHv3UVnJ3sp

**Comment by hybridherbst** [comment]
@sylwesterdigital you may want to check https://twitter.com/hybridherbst/status/1584524129054904321

**Comment by hybridherbst** [comment]
I believe this issue can be closed as the problem has been resolved for a while. Thanks all!
