### ISSUE TITLE
Is there a Semi-Transparent Hand Model?

### ISSUE THREAD

**Issue by Carton22** [immersive-web/webxr-input-profiles#256]
**Profile Id**
The profile id for which the asset should be added

**Do you have an existing MIT licensed 3D asset to submit**
Yes/No

No

Is there an existing semi-transparent hand model like this we can use👇?
Or how could we make the provided generic hand model into a semi-transparent one?

Thanks!

![opacity](https://github.com/immersive-web/webxr-input-profiles/assets/68193543/e5a24fd8-5275-4c58-afd3-133d34df4d2c)

**Comment by toji** [comment]
We're unlikely to offer mesh variants with alternate materials, sorry!

What "semi-transparent" means is going to be a somewhat context dependent. For example, some applications may want a traditional blend with varying opacities, others may want an additive effect, while yet others would want the hands to darken the underlying scene. Some may want the wrists to fade out, while others may prefer a clean line. Also, in the example image you posted the hands have an outline effect, which isn't something that could be baked into the distributed glTF files, it would need to be implemented in the application.

The hands that we do distribute are very generic and have a plain white material, so it's likely that you could simply adjust the opacity of the meshes to 0.5 or similar after they've loaded in your rendering engine of choice to get part of the effect you're looking for.
