### ISSUE TITLE
Decide on versioning semantics

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr-input-profiles#26]
In the context of a major/minor/patch version scheme, we need to decide which types of changes to this repo would trigger a version bump.  Throwing down a first proposal, I suggest:

**Patch**
* Adding new mapping and asset files
* Fixes to existing mapping or asset files

**Minor**
* Fixing bugs in source code
* Fixing bugs in tests
* Non-breaking schema changes (additive features)
* Non-breaking source changes (additive features)

**Major**
* Breaking schema changes
* Breaking source changes

Additionally, I'm wondering what we want to do about the version property in the mapping files.  It seems a bit much to rev the version # in a mapping file simply because a new mapping file was added.  Perhaps we change the version property in the mapping.json files to just be major/minor?

**Comment by NellWaliczek** [comment]
Based on several discussions over the past few days, I'm updating the proposal to as follows.  The key aspect of this proposal is that mapping.json file versions will only update when a major/minor version bump occurs.

#### Patch
* Adds new mapping and/or asset files
* Fixes to existing mapping and/or asset files
* Critical security fixes
* Occasional non-breaking fixes to schema, source code, or test code

#### Minor
* Additional features added 
* Small breaking changes to schema
* Breaking changes in source code or test code

#### Major
* Significant design changes

**Comment by NellWaliczek** [comment]
Related to this, what should the branch structure be to allow automatic publishing when a new release is generated?

**Comment by toji** [comment]
Added Nell's breakdown of the versioning from this issue to the repo's README, since I believe it's still an accurate representation of how we intend to manage the package versioning.
