### ISSUE TITLE
Add a `generic-hand-static` model.

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr-input-profiles#260]
**Profile Id**
There may be a new profile with `generic-hand-static` for the situation where users are using hands for interaction but the hand-tracking features are not present. Currently the `generic-hand` model isn't super appropriate for this. Ideally the asset should have:

* No joints
* Natural Pose
* Some animation which represents button[0]

**Do you have an existing MIT licensed 3D asset to submit**
No

**Comment by AdaRoseCannon** [comment]
Something like this is what I had in mind:

<img width="452" alt="image" src="https://github.com/immersive-web/webxr-input-profiles/assets/4225330/e769e1c5-8b1a-4d52-ad7b-ae06f9670e92">

**Comment by toji** [comment]
I think that would work out nicely. For the record, this is the current hand mesh in it's bind pose:

![Screenshot from 2024-06-11 14-16-35](https://github.com/immersive-web/webxr-input-profiles/assets/805273/b20ee64c-9945-4df9-85e3-767a94179b0e)

![Screenshot from 2024-06-11 14-16-49](https://github.com/immersive-web/webxr-input-profiles/assets/805273/a4dd0563-0a4b-4901-9144-60ca3316b535)

The pose isn't quite as rigid or splayed as I had thought, but it's still not quite what I would consider a relaxed or natural pose so I think it's reasonable (though not strictly necessary) to give a static version of the asset a more naturalistic pose, especially if we consider that most people using hands in this mode _are_ going to be doing tap gestures as their primary input.

Regarding the ball, I think it's a reasonable visual affordance to differentiate from a more fully feature hand. I think we can rig it in such a way that the sphere can show/hide/expand/contract when an input event is detected. What do you think would be most natural in that regard? Show it initially and hide or shrink when the user taps, or hide/shrink it initially and show/grow it when the user taps?

**Comment by toji** [comment]
Also, several people on the call today voiced support for `generic-static-hand` as the input profile string, which sounds fine to me as well.

**Comment by AdaRoseCannon** [comment]
alcooper raised it might be useful to have `-static` as a suffix and Brandel raised that `meta-static-hand` is a deeply unpleasant name compared to `meta-hand-static`.

**Comment by toji** [comment]
Ah, I didn't quite hear Brandel's comment about `meta-static-hand`. And yeah, I agree! Thanks for clarifying!

**Comment by toji** [comment]
Welp, that's unfortunate.

I did a quick experiment with this tonight, and it looks like shrinking or growing a ball isn't going to work (at least not without some library modifications.) The library and at least the Three.js implementation work exclusively with position and orientation values, mimicking the `XRRigidTransform` properties. So scaling is ignored. There IS a mechanism for changing the visibility of a node, though, so we could use that to do things like make the ball visible or swap colors.

**Comment by AdaRoseCannon** [comment]
Making it visible when you are pinching seems like an adequate fallback. I don't think it is worth adding scale functionality until at least one real controller needs it for something.

**Comment by cabanier** [comment]
> alcooper raised it might be useful to have `-static` as a suffix and Brandel raised that `meta-static-hand` is a deeply unpleasant name compared to `meta-hand-static`.

I believe @alcooper91 said that it makes more sense to have `generic-static-` as a prefix since that could apply to more than just hands.
If people don't like `meta-static`, I can rename it to `meta-fixed` since vendors can pick their own name.

**Comment by AdaRoseCannon** [comment]
That works! How do you feel about the hand pose in the first image?

**Comment by alcooper91** [comment]
> I believe @alcooper91 said that it makes more sense to have generic-static- as a prefix since that could apply to more than just hands.

Yeah, I think "generic-static" establishes a pattern interface that can be re-used more in the future; (e.g. generic-static-tracker or something); agree that meta-static may be undesirable/unfortunate though, and would loosely prefer to keep a similar nomenclature across the board , so perhaps `generic-fixed` would be better as well then?

My only concern with the first image is to ensure that it actually aligns appropriately with the grip pose to roughly match the user's actual hand position, and that we aren't enforcing any kind of "pointing" (as it sounded like you were suggesting that on the call, but maybe I misunderstood)

**Comment by toji** [comment]
My minor concern about `generic-fixed-` is that it could be interpreted as "The old was was broken, and we fixed it in this one." rather than "fixed-as-in-immobile". I don't think I would object if everyone else still wanted to use it, though.

Other possibilities:

 - `generic-stationary-hand`
 - `generic-rigid-hand`
 - `generic-immobile-hand`
 - `generic-frozen-hand`
 - `generic-locked-hand`
 - `generic-hand-emulated-controller`
 - `generic-unskinned-hand` (Hm... on second thought... maybe lets not talk about hands with no skin...)

**Comment by cabanier** [comment]
> Making it visible when you are pinching seems like an adequate fallback. I don't think it is worth adding scale functionality until at least one real controller needs it for something.

I think it looks great. We can submit it and if needed we can always change it later.

**Comment by alcooper91** [comment]
`generic-emulated-hand` feels like it sets up a decent hierarchy for other emulated type objects as well, and we have a notion of things like that? Could even be used on emulators.

**Comment by cabanier** [comment]
> `generic-emulated-hand` feels like it sets up a decent hierarchy for other emulated type objects as well, and we have a notion of things like that? Could even be used on emulators.

I like `generic-emulated-hand' as well.

**Comment by toji** [comment]
So I thought about that, but it feels a bit backwards to me. It's actually a hand emulating a controller, rather than an emulated hand (because it is an *actual* hand, just without joint data.) An emulated hand, to me, would be something like creating an approximated hand mesh from controller inputs or via simulator tooling.

But maybe I'm just being too pedantic?

**Comment by cabanier** [comment]
@toji If you add the profile and metadata, I will add `meta-fixed-hand`

**Comment by toji** [comment]
I'll have a PR up by end of day

**Comment by alcooper91** [comment]
If it's not too late to toss one more bikeshed color into the mix:

`generic-palm`, since essentially what you'd be getting in this state would be the palm pose+notifications of any defined buttons?

**Comment by AdaRoseCannon** [comment]
> My only concern with the first image is to ensure that it actually aligns appropriately with the grip pose to roughly match the user's actual hand position, and that we aren't enforcing any kind of "pointing" (as it sounded like you were suggesting that on the call, but maybe I misunderstood)

By pointing I mean as in it has a little directionality rather than literally pointing with a finger. This pose is what I was going for:

<img width="330" alt="image" src="https://github.com/immersive-web/webxr-input-profiles/assets/4225330/cffad233-0962-4c1c-9793-2e0dac43bfe9">

**Comment by toji** [comment]
> `generic-palm`, since essentially what you'd be getting in this state would be the palm pose+notifications of any defined buttons?

Only if we can use this as the GLB asset. :wink: 
![tumblr_c8590a7eb5a24939a9e46e90f19b4356_70b4bd6c_540](https://github.com/immersive-web/webxr-input-profiles/assets/805273/94d8ea3c-b5e6-4fb0-a1a8-6f92c2a1fea5)

**Comment by toji** [comment]
https://github.com/immersive-web/webxr-input-profiles/pull/261 is now merged, which gives us the `generic-fixed-hand` profile in the registry. We'll get an asset working next. Ada has already sent over a mesh that matches her concept from earlier in the thread, I just want to do a bit of verification to make sure it's working the way we expect it to in the scenarios we want it to before putting up a patch.

**Comment by toji** [comment]
Relevant asset was added in #263, so this issue can now be closed.

**Comment by cabanier** [comment]
Quest browser was released last week with support for this.
