### ISSUE TITLE
Oculus Quest mapping

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/webxr-input-profiles#44]
Just FYI: Oculus Quest controllers mapping is exactly the same as Oculus Touch one. More over, even the name of the controller is the same, including the gamepad id (at least, currently; this is done for compatibility reasons in WebVR with existing Oculus Touch-enabled experiences). The only difference is the 3D model of the controllers, but to determine this you'd need to check the name of the headset (at the moment).

**Comment by NellWaliczek** [comment]
> The only difference is the 3D model of the controllers, but to determine this you'd need to check the name of the headset (at the moment).

That's really unfortunate to hear.  That means, with the current designs, this library isn't going to work for displaying the controllers with a correct visual for WebVR.

**Comment by Artyom17** [comment]
Well, this is how it is now; we are discussing different naming schema [here](https://github.com/immersive-web/webxr/issues/550) anyway.

**Comment by NellWaliczek** [comment]
>Is it possible to add an additional field that reflects vrDisplay.displayName?

Yeah, that's kinda what I was thinking.  Maybe add a property to each handedness entry:

```json
{
    "id" : "Oculus Touch (Left)",
    "webVR": true,
    "handedness" : {
        "left" : {
            "asset" : "some-url",
            "webVR_additionalAsset" : {
                "displayName" : "Oculus Quest",
                "asset" : "some-url"
            }
        }
    }
}
```

**Comment by NellWaliczek** [comment]
I believe this has now been addressed in WebXR.  @Artyom17 Are you still hoping to address this for WebVR gamepads?

**Comment by NellWaliczek** [comment]
@toji and I have agreed that the best thing to do is remove all WebVR specific references from this repository and let the webxr polyfill handle any translation necessary.  To that end, @Artyom17 , can you verify that this polyfill PR will meet your need?  If so, this issue should be closed when the PR is merged https://github.com/immersive-web/webxr-polyfill/pull/72/files#diff-17ea53cf6f8464bfcfad7c0aa3480ef6R68

**Comment by NellWaliczek** [comment]
All webvr specific content has been removed in PR #78 in favor of relying on the polyfill.  Please file an issue over there if there is still something that needs to be addressed
