### ISSUE TITLE
UA reserved buttons

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr-input-profiles#82]
The WebXR Gamepads Module states "Buttons reserved by the UA or platform MUST NOT be exposed."

This is fairly straighforward for platform reserved buttons, but needs to be clarified on a device-by-device basis for any UA reserved buttons.  The schema for the registry should be updated to provide a mechanism for defining this consistency.

**Comment by NellWaliczek** [comment]
@thetuvix, @jacobcdewitt, @Manishearth  How would you like to proceed with this?

**Comment by Manishearth** [comment]
I was thinking that you declare it under `components` as `xr-standard-app-button: {type: button}` or something, and use it in `gamepad`. UAs are required to not expose the button

Alternatively, we could do this as a separate field on a layout, perhaps? I don't have strong opinions. I would like us to err on the side of _having_ an app button on any given controller.

**Comment by NellWaliczek** [comment]
I'll take a poke at the right schema changes to support tracking this in the registry.  In the meanwhile...

/agenda To learn which buttons should be documented as reserved for each profile
