### ISSUE TITLE
The term "source" is overloaded across the schemas

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-input-profiles#86]
The terms "component" is used consistently across WebXR and this repo, while the term "source" is quite overloaded.

**Component**
* [`layouts.*.components`](https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/README.md#components): The parts of an input source.

**Source**
* `XRInputSource`: An entire controller.
* [`visualResponses.source`](https://github.com/immersive-web/webxr-input-profiles/tree/master/packages/assets#visual-responses): The kind of a source's component's state that affects a visual response.
* [`selectSource`](https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/schemas/layout.schema.json): The ID of the component used for `onselect` events.

This ambiguity has continued to confuse me as I dig through the profiles, trying to keep straight exactly how the various entities connect.

**Strawman:**
For `selectSource`, we could rename it to `selectComponentId`.

For `visualResponses.source`, my instinct was to rename it to `property`, but that is used by `"property": "visibility"`.  We could rename it to something like `data` or `field` instead.

**Comment by NellWaliczek** [comment]
`selectSource` -> `selectComponentId` sounds good to me

`visualResponse.source`->`visualResponse.data` or maybe `componentValue`?

**Comment by thetuvix** [comment]
It may be worth making the `selectSource` half of the change now, since it impacts the `registry` package.
