### ISSUE TITLE
Referenced node names should be unique within a model

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-input-profiles#88]
One piece of feedback we've gotten around Windows MR's glTF-based controller models is that it's awkward to deal with ambiguous node names like `"UNPRESSED"` that only get their context by the name of their ancestor node (e.g. an `"UNPRESSED"` node that is a child of a `"GRASP"` node).

This is for two reasons:
* Code for rendering/articulating the controller model can more easily just look up the one node in the model with a given name, rather than finding an ancestor node with one name and then searching through its descendant nodes to find another name.
* glTF tools for authoring/transforming models in the first place can often expect that node names are globally unique within the model.

It may simplify things to establish a stronger rule here than we'd established in the native WinMR render model APIs, and just require that node names referenced in the assets profile show up only once in a given glTF file.  For the example above, the `"UNPRESSED"` node under `"GRASP"` would be renamed to `"GRASP_UNPRESSED"`.  This could also remove the need for profiles to specify the `rootNodeName` for each component and visual response, unless we want those for other reasons.

**Comment by NellWaliczek** [comment]
Fixed by #118
