### ISSUE TITLE
Fixed convention about glTF node names?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-input-profiles#89]
As I wrote up how #88 could simplify node references, I wanted to confirm that we really do need the indirection of allowing profiles to target model-specific node names vs. simply defining well-known names for these glTF nodes.

For example, here is a current `component` definition for an `"xr-standard-thumbstick"` component:
```json
"xr-standard-thumbstick" : {
    "rootNodeName" : "THUMBSTICK_PRESS",
    "labelAnchorNodeName" : "thumbstick-label",
    "visualResponses": [
        {
            "rootNodeName": "THUMBSTICK_PRESS",
            "source" : "state",
            "states" : ["pressed"],
            "minNodeName": "UNPRESSED",
            "maxNodeName": "PRESSED"
        },
        {
            "rootNodeName": "THUMBSTICK_X",
            "source" : "xAxis",
            "states" : ["default", "touched", "pressed"]
        },
        {
            "rootNodeName": "THUMBSTICK_Y",
            "source" : "yAxis",
            "states" : ["default", "touched", "pressed"]
        }
    ]
},
```

However, imagine that the rendering library simply observes the model to have the following nodes:
* _(any name)_
  * `xr-standard-thumbstick-pressed-min`
  * `xr-standard-thumbstick-pressed-max`
  * `xr-standard-thumbstick-pressed-value`
    * _(any name)_
      * `xr-standard-thumbstick-xaxis-min`
      * `xr-standard-thumbstick-xaxis-max`
      * `xr-standard-thumbstick-xaxis-value`
        * _(any name)_
          * `xr-standard-thumbstick-yaxis-min`
          * `xr-standard-thumbstick-yaxis-max`
          * `xr-standard-thumbstick-yaxis-value`
            * _(any name)_
  * `xr-standard-thumbstick-label`

At that point, the rendering library can know purely by convention how to articulate the `"xr-standard-thumbstick"` component of that input source and find its label node.

Profiles could still define custom components such as `"a-button"`, which would then follow the same `pressed` naming convention:
* _(any name)_
  * `a-button-pressed-min`
  * `a-button-pressed-max`
  * `a-button-pressed-value`

Do you see ways in which this kind of convention could limit how model authors lay out their models?  For example, have you encountered cases where a thumbstick's `"default"`, `"touched"` and `"pressed"` states won't all articulate the same glTF nodes?

If not, moving to a convention-based system could greatly simplify the asset profile schema, and remove many points of naming divergence across profiles.  This could avoid bugs later on where alternate rendering libraries end up taking dependencies on what they believed to be naming conventions in the profiles they looked at (e.g. they observe the trigger is often called "SELECT") but which we'd reserved the right to indirect through the profile (e.g. they end up with a controller where it's called "TRIGGER").  We'd still reserve the right to add in any necessary overrides down the line, while avoiding indirection in advance that may not be needed.

Thoughts?

**Comment by NellWaliczek** [comment]
Fixed by #118
