### ISSUE TITLE
The term "grip" in WebXR conflicts with the meaning in profile names

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-input-profiles#90]
The term "grip" is used in the WebXR API as part of `gripSpace`, to refer to the point in the user's controller or hand at the center of the user's grip.

As used so far in the [input profiles registry](https://github.com/immersive-web/webxr-input-profiles/blob/master/packages/registry/profiles/generic/generic-trigger-grip-touchpad-thumbstick.json), "grip" is referring to the button/trigger on the side of the controller pressed when the user squeezes the controller.  While this button often happens to be _near_ the origin of `gripSpace`, it's logically a distinct concept.

This issue tracks the more urgent registry profile impact from my suggestion in https://github.com/immersive-web/webxr-gamepads-module/issues/2#issuecomment-532522768 to adopt the term **`squeeze`** for the grip component to resolve this ambiguity, which would result in the following generic profile names:
* `generic-button`
* `generic-touchpad`
* `generic-trigger`
* `generic-trigger-squeeze`
* `generic-trigger-squeeze-thumbstick`
* `generic-trigger-squeeze-touchpad`
* `generic-trigger-squeeze-touchpad-thumbstick`
* `generic-trigger-thumbstick`
* `generic-trigger-touchpad`
* `generic-trigger-touchpad-thumbstick`

**Comment by NellWaliczek** [comment]
Fixed by #91
