### ISSUE TITLE
Enum values should use "hyphen-case" rather than "camelCase"

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-input-profiles#92]
There were a few enum values I saw that were using `"camelCase"` rather than `"hyphen-case"`.

Here's the ones I noticed in the registry:
* `"faceButton"`
* `"xAxis"`/`"yAxis"`

**Comment by NellWaliczek** [comment]
So "faceButton" isn't an enum value, but the other two are.  Do we want to restrict component names to follow the same formatting rules as profile ids?

**Comment by thetuvix** [comment]
We are otherwise following that pattern for component names - it seems reasonable to make it a rule.
