### ISSUE TITLE
Should "valve-index" fall back to "htc-vive"?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr-input-profiles#98]
Ok, so here's a question... is this actually the desired behavior for the valve index?  Or would it be better to skip the `htc-vive` fallback since there is actually a generic variant that can be used?

_Originally posted by @NellWaliczek in https://github.com/immersive-web/webxr/pull/851_

**Comment by Manishearth** [comment]
Also interested in hearing thoughts on https://github.com/immersive-web/webxr-input-profiles/issues/99 , which affects how urgent this issue is.

**Comment by NellWaliczek** [comment]
Actually looking at this more closely, the answer here is definitely "no".  The htc-vive has no thumbstick and does have a menu button.  The valve-index does have a thumbstick but no menu button.

Please reopen if there is an objection.
